//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutID { get; set; }
        public string AboutTitle { get; set; }
        public string CvLink { get; set; }
        public string AboutShort { get; set; }
        public string AboutImage { get; set; }
    }
}
