//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAchievementDetail
    {
        public int Id { get; set; }
        public string SmallTitle { get; set; }
        public string Title { get; set; }
        public string Skill1Title { get; set; }
        public string Skill1Description { get; set; }
        public string Skill2Title { get; set; }
        public string Skill2Description { get; set; }
        public string Skill3Title { get; set; }
        public string Skill3Description { get; set; }
        public string Skill4Title { get; set; }
        public string Skill4Description { get; set; }
    }
}
